portfolio:
  name: 은주 포트폴리오
  base_currency: KRW
accounts:
- id: kiwoom
  name: 키움증권
- id: other
  name: 다른증권사
holdings:
- ticker: '000660'
  name: SK하이닉스
  quantity: 7
  buy_price: 908571.0
  account: kiwoom
  type: stock
- ticker: 005930
  name: 삼성전자
  quantity: 36
  buy_price: 185653.0
  account: kiwoom
  type: stock
- ticker: '171090'
  name: 선익시스템
  quantity: 51
  buy_price: 99201.0
  account: kiwoom
  type: stock
- ticker: '475150'
  name: SK이터닉스
  quantity: 40
  buy_price: 42944.0
  account: kiwoom
  type: stock
- ticker: '006400'
  name: 삼성SDI
  quantity: 5
  buy_price: 387600.0
  account: kiwoom
  type: stock
- ticker: 009830
  name: 한화솔루션
  quantity: 47
  buy_price: 42921.0
  account: kiwoom
  type: stock
- ticker: '034020'
  name: 두산에너빌리티
  quantity: 13
  buy_price: 93000.0
  account: kiwoom
  type: stock
- ticker: '272210'
  name: 한화시스템
  quantity: 10
  buy_price: 145750.0
  account: kiwoom
  type: stock
- ticker: 085910
  name: 네오티스
  quantity: 55
  buy_price: 19760.0
  account: kiwoom
  type: stock
- ticker: 032820
  name: 우리기술
  quantity: 50
  buy_price: 28900.0
  account: other
  type: stock
- ticker: '491000'
  name: 리브스메드
  quantity: 14
  buy_price: 84286.0
  account: other
  type: stock
- ticker: '187660'
  name: 페니트리움바이오
  quantity: 80
  buy_price: 15200.0
  account: other
  type: stock
- ticker: 091160
  name: KODEX 반도체
  quantity: 10
  buy_price: 101900.0
  account: other
  type: etf
- ticker: '047040'
  name: 대우건설
  quantity: 83
  buy_price: 12659.0
  account: other
  type: stock
- ticker: '015760'
  name: 한국전력
  quantity: 20
  buy_price: 48050.0
  account: other
  type: stock
- ticker: 025860
  name: 남해화학
  quantity: 100
  buy_price: 8550.0
  account: other
  type: stock
- ticker: 011930
  name: 신성이엔지
  quantity: 300
  buy_price: 3050.0
  account: other
  type: stock
- ticker: '047050'
  name: 포스코인터내셔널
  quantity: 10
  buy_price: 74500.0
  account: other
  type: stock
- ticker: '323410'
  name: 카카오뱅크
  quantity: 30
  buy_price: 27000.0
  account: other
  type: stock
- ticker: '042660'
  name: 한화오션
  quantity: 5
  buy_price: 122000.0
  account: other
  type: stock
- ticker: '399720'
  name: 가온칩스
  quantity: 10
  buy_price: 59700.0
  account: other
  type: stock
- ticker: '229200'
  name: KODEX 코스닥150
  quantity: 30
  buy_price: 20800.0
  account: other
  type: etf
- ticker: '277640'
  name: TIGER 코스피대형주
  quantity: 20
  buy_price: 30410.0
  account: other
  type: etf
- ticker: '001510'
  name: SK증권
  quantity: 266
  buy_price: 2244.0
  account: other
  type: stock
- ticker: '279570'
  name: 케이뱅크
  quantity: 78
  buy_price: 9124.0
  account: other
  type: stock
- ticker: '055550'
  name: 신한지주
  quantity: 5
  buy_price: 96700.0
  account: other
  type: stock
- ticker: '242040'
  name: 나무기술
  quantity: 50
  buy_price: 7150.0
  account: other
  type: stock
- ticker: '004060'
  name: SG세계물산
  quantity: 534
  buy_price: 530.0
  account: other
  type: stock
- ticker: 024840
  name: KB메탈
  quantity: 96
  buy_price: 2500.0
  account: other
  type: stock
- ticker: '130660'
  name: 한전산업
  quantity: 11
  buy_price: 23000.0
  account: other
  type: stock
- ticker: '004020'
  name: 현대제철
  quantity: 4
  buy_price: 38375.0
  account: other
  type: stock
- ticker: 018880
  name: 한온시스템
  quantity: 23
  buy_price: 4380.0
  account: other
  type: stock
- ticker: IVV
  name: iShares S&P500
  quantity: 2
  buy_price: 642.87
  account: kiwoom
  type: us_stock
  currency: USD
- ticker: QQQA
  name: ProShares Nasdaq-100 모멘텀
  quantity: 14
  buy_price: 51.5671
  account: kiwoom
  type: us_stock
  currency: USD
- ticker: NVDA
  name: 엔비디아
  quantity: 3
  buy_price: 175.0
  account: kiwoom
  type: us_stock
  currency: USD
- ticker: COHR
  name: 코히어런트
  quantity: 2
  buy_price: 254.0
  account: kiwoom
  type: us_stock
  currency: USD
- ticker: QQQM
  name: 'Invesco Nasdaq-100 '
  quantity: 2
  buy_price: 233.045
  account: kiwoom
  type: us_stock
  currency: USD
- ticker: PLTR
  name: 팔란티어 테크
  quantity: 3
  buy_price: 148.735
  account: kiwoom
  type: us_stock
  currency: USD
- ticker: AMD
  name: AMD
  quantity: 2
  buy_price: 211.8
  account: kiwoom
  type: us_stock
  currency: USD
- ticker: FIG
  name: 피그마
  quantity: 15
  buy_price: 28.0533
  account: kiwoom
  type: us_stock
  currency: USD
- ticker: SMX
  name: SMX 시큐리티
  quantity: 2
  buy_price: 80.0
  account: kiwoom
  type: us_stock
  currency: USD
- ticker: '465580'
  name: ACE 미국빅테크TOP7Plus
  quantity: 15
  buy_price: 21310.0
  account: kiwoom
  type: stock
- ticker: '491010'
  name: TIGER 글로벌 AI전력인프라엑티브
  quantity: 11
  buy_price: 23734.0
  account: other
  type: stock
- ticker: '475070'
  name: KoAct 글로벌친환경전력인프라엑티브
  quantity: 2
  buy_price: 31450.0
  account: other
  type: stock
